apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    env: prod
    app: ic-webapp
  name: ic-webapp
  namespace: ic-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-webapp
  template:
    metadata:
      labels:
        app: ic-webapp
    spec:
      containers:
        - name: ic-webapp
          image: mike971/ic-webapp:v1.0
          env:
            - name: ODOO_URL
              value: http://192.168.56.1:30069/
            - name: PGADMIN_URL
              value: http://192.168.56.1:30050/
          ports:
            - containerPort: 8080
              name: ic-webapp
