kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # Expose le port 30007 sur l'hôte, qui mappe le NodePort du service dans le cluster.
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
      - containerPort: 30050
        hostPort: 30050
        protocol: TCP
      - containerPort: 30069
        hostPort: 30069
        protocol: TCP