apiVersion: v1
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "docker_postgres",
          "Group": "docker_postgres_group",
          "Host": "postgres",
          "Port": "5432",
          "MaintenanceDB": "postgres",
          "Username": "odoo_user",
          "SSLMode": "prefer"
        }
      }
    }
kind: ConfigMap
metadata:
  namespace: ic-webapp
  name: pgadmin-config
  labels:
    env: prod